javascript pay sdk improve examples and docs
XcooBee/payment-sdk-js pull request #3
Opened 2020-07-22 08:58 UTC by shablenko-sednor

add minified version of sdk, expose global variables for browser

2020-07-22 08:58 UTC, sergey-shablenko commented
![](https://github.trello.services/images/mini-trello-icon.png) [javascript pay sdk improve examples and docs](https://trello.com/c/0010C2m7/3722-javascript-pay-sdk-improve-examples-and-docs)

2020-07-23 14:51 UTC, dhurlburtusa requested changes

2020-07-23 14:51 UTC, dhurlburtusa commented on package.json
> +    "cross-env": "^7.0.2",
Please move this to `devDependencies`.

2020-07-23 15:00 UTC, dhurlburtusa approved these changes

2020-07-24 15:50 UTC, merged